### ISSUE TITLE
IPv6 not working

### ISSUE THREAD

**Issue by thomasschaeferm** [likwidoxigen/mt7610u_wifi#3]
Update: I made some test with different notebooks: 
32bit works(i686) 
64bit doesn't (x86_64) 

Kernel was 3.16.7-21 in all cases.

Do I have to change some settings in Makefile?

The situation: iPv6 via WLAN via R216 (WLAN/LTE-Router) with NAT64, IPv4 only local and Routermanagement

ping 192.168.0.1 (router) works

also assigning all addresses (IPv4, IPv6 via RA and DHCPv6, DNS-resolver) works

But IPv6 connections are not possible - ping says: Destination unreachable: Address unreachable.

The combination of this router and notebook works in general - I made this test also with the built in wlan-device. But I bought the ac51 for using 5Ghz.

Maybe somebody has an idea. I can provide logfile or do tests.

PS: I verified this problem with a different router. (avm fritzbox dualstack, same Problem: Ipv4 works, IPv6 doesn't work)

**Comment by thomasschaeferm** [comment]
At a different 64bit-notebook it works. 
Therefore it maybe not a general problem.

**Comment by likwidoxigen** [comment]
Thanks for updating this. I've been trying to get some info but my Lenovo just kicks to a reboot after about 3 minutes so it was difficult getting any good information before that happened
